spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dev-potential-rds.cykogeenkfuk.ap-northeast-2.rds.amazonaws.com:54321/potential
    username: postgres
    password: potential4305
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  jdbc:
    template:
      max-rows: 100
      query-timeout: 7200
logging:
  level:
    org.hibernate.SQL: debug
