server:
    port: 8081

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

file:
  basePath: /Users
---

spring:
  profiles: js_dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/market
#    username: root
#    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
    username: sa
    password:

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/

  mvc:
    view:
      suffix: .html

logging:
  level:
    org.hibernate.SQL: debug

file:
  basePath: /Users/wotjd4305/Desktop/dev

